wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682070994.834322
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.10
      5: 0.14.2
      6: 4.28.1
      8:
      - 5
